---
title: "PalmerPenguins"
author: "Fabiola Zamora"
date: "`r Sys.Date()`"
output: html_document
---
# Fabiola Gonzalez Zamora
## Week 3

```{r Setup, include=FALSE}
library(palmerpenguins)
library(tidyverse)
library(ggplot2)
library(praise)
library(colorBlindness)
library(ggthemes)
library(here)
library(maps)

# Currently available from GitHub, use peRReo pallette
# install.packages("devtools")
library(devtools)
library(peRReo)
```
  
```{r Grammar of ggplot, include=FALSE}
# Practice from Week 3, Part 1 of Lecture

# Start with penguin dataframe

penguinplot <- ggplot(data = penguins, 
       mapping = aes(x = bill_depth_mm, # Map bill depth to x-axis 
                     y = bill_length_mm, # Map bill length to y-axis
                     color = species)) + # Map species to the colour of each point
  geom_point() + 
  labs(title = "Bill depth and length", # Title the plot
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", # Add subtitle
       x = "Bill depth (mm)", y = "Bill length (mm)", # Label x and y axes
       color = "Species", # Label legend species 
       caption = "Source: Palmer Station LTER / palmerpenguins package") +
  scale_color_viridis_d() # Use a discrete color scales

penguinplot # View First Plot

# Practice from Week 3, Part 2 of Lecture

penguinplot1 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +
  geom_point() + 
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       )
penguinplot1

# Adding a best fit line

penguinplot2 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       )

penguinplot2

# look up different methods using ?geom_smooth

# Size vs. Line Width
  # geom_smooth(linewidth = 2) # current, correct syntax
  # geom_smooth(size = 2) # still runs, but triggers a deprecation warning

# Making a Linear Model
  # There are 3 different species in this data, how should we group them?

penguinplot3 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) + # Add some colors by species
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       )

penguinplot3

```


```{r Faceting, include=FALSE}
# Multiple plots groups by species on the y (rows) and and sex on the x (columns)
ggplot(penguins, 
       aes(x = bill_depth_mm,
           y = bill_length_mm))+
  geom_point()+
  facet_grid(species~sex)

# Wrap by species
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + 
  geom_point() +
  facet_wrap(~ species)

# Make it two columns
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + 
  geom_point() +
  facet_wrap(~ species, ncol=2)

# Facet and color
ggplot(data=penguins, 
  mapping = aes(x = bill_depth_mm,
                y = bill_length_mm,
                color = species,
                )) +
  geom_point()+
  scale_color_viridis_d()+
  facet_grid(species~sex)
```
```{r Scales, include=FALSE}
# Playing with change of scale
penguinplot4 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_viridis_d()+
  scale_x_continuous(limits = c(0, 20)) # Set x limits

penguinplot4

# Change x breaks

penguinplot5 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14, 17, 21),
                     labels = c("low", "medium", "high"))
  
penguinplot5

# Manually change color scale
penguinplot6 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = c("orange", "purple", "green"))

penguinplot6

# Using peRReo palette 

pal = latin_palette('daddy2', 3)

penguinplot7 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)

penguinplot7

```
```{r Coordinates, include=FALSE}
# Flip the axes
penguinplot8 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)+
  coord_flip() # flip x and y axes

penguinplot8

# Fix axes
penguinplot9 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)+
  coord_flip() # flip x and y axes

penguinplot9

# Transform the x and y-axis, using different data set
ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  coord_trans(x = "log10", y = "log10")

# Make the plot polar
penguinplot10 <- ggplot(data=penguins, 
  mapping = aes(x = bill_depth_mm,
                y = bill_length_mm,
                group = species,
                color = species)) + 
  geom_point()+ 
  geom_smooth(method = "lm")+ 
   labs(x = "Bill depth (mm)", 
        y = "Bill length (mm)"
        ) +
  scale_color_manual(values = pal) +
  coord_polar("x") # make the polar

penguinplot10
```

```{r Themes, include=FALSE}
penguinplot11 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)+
  theme_classic()

penguinplot12

# More customizations of themes
penguinplot12 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)+
  theme_classic()+
  theme(axis.title = element_text(size = 18, # change size 
                                 color = "red")) # change color

penguinplot12

# Change the background color
penguinplot13 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Bill depth (mm)",
       y = "Bill length (mm)"
       ) +
  scale_color_manual(values = pal)+
  theme_classic()+
  theme(axis.title = element_text(size = 18,
                                 color = "red"),
        panel.background = element_rect(fill = "linen"))

penguinplot13
```
```{r Saving Plots, include=FALSE}
ggsave(here("Week_03", "Output","penguin.png"))

ggsave(here("Week_03", "Output", "penguinsmall.png"),
       width = 5, height = 5)
```

```{r Homework, Create New Plot}
# Using peRReo palette, Natti Nattasha palette for the different species 
pal = latin_palette("natti", 3) # Species colors

axis = latin_palette("calle13") # Axes color

# Using peRReo palette, Bad Bunny palette for panel background
isl = scales::alpha(
  latin_palette("badbunny1", 1),
  alpha = 0.2) 

penguins_clean <- penguins %>%
  drop_na(bill_length_mm, island, species) # Remove any observations without a recorded bill length

# Display bill-length density separately for each island
bill_length_plot <- ggplot(
  data = penguins_clean, # Use cleaned data
  mapping = aes(
    x = bill_length_mm,
    fill = species,
    color = species)) +
  geom_density(
    alpha = 0.67,
    linewidth = 0.67) +
  facet_wrap(~ island, ncol = 1) + # Facet plots groups by island
  scale_color_manual(values = pal) +
  scale_fill_manual(values = pal) +
  labs(
    title = "Penguin Bill Lengths among Palmer Archipelago Islands",
    x = "Bill length (mm)",
    y = "Density",
    fill = "Species",
    color = "Species",
    caption = "Source: Palmer Station LTER / palmerpenguins") +
  theme_base() +
  theme(plot.title = element_text(size = 15),
        axis.title.x = element_text(size = 13,
                                    color = axis,
                                    face = "bold"),
        axis.title.y = element_text(size = 13,
                                    color = axis,
                                    face = "bold"),
        legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 9),
        legend.background = element_rect( # Add background block to background text
          color = isl,
          fill = isl,
        ),
        plot.caption = element_text(size = 8), # Adjust plot caption text size
       panel.background = element_rect(fill = isl) # Change the background color of panels
  )

bill_length_plot

# Save plot in output folder
ggsave(here("Week_03", "Output", "bill_length_by_island.png"),
  plot = bill_length_plot)

```


